### ISSUE TITLE
custom features "onclick" doesn't work 

### ISSUE THREAD

**Issue by gpfr** [JohnCoene/echarts4r#51]
Hi,

First of all. Thank you for this great package.

I tried to create a custom feature as described at:

https://ecomfe.github.io/echarts-doc/public/en/option.html#toolbox.feature

After creating an echart object "ech" I added the feature:

```
    myTool1=list(
        show=T
        ,title='custom extension method 1'
        ,icon= 'image://http://echarts.baidu.com/images/favicon.png'
        ,onclick="myfunc()"
    )
    ech$x$opts$toolbox$feature$myTool1=myTool1
```

After doing so I can see a new icon at the top right corner of the plot, but when I click the button it doesn't work. In the browser's console you can see the error:

```
VM22989:22 Uncaught TypeError: t.apply is not a function
    at kn.eval (eval at <anonymous> (jquery.min.js:formatted:143), <anonymous>:22:2321)
    at kn.trigger (eval at <anonymous> (jquery.min.js:formatted:143), <anonymous>:22:235920)
    at cw.dispatchToElement (eval at <anonymous> (jquery.min.js:formatted:143), <anonymous>:22:238322)
    at cw.(:8787/p/5397/anonymous function) [as click] (eval at <anonymous> (http://35.195.31.49:8787/p/5397/shared/jquery.min.js:2:2651), <anonymous>:22:239159)
    at Mi.trigger (eval at <anonymous> (jquery.min.js:formatted:143), <anonymous>:22:235920)
    at Mi.Ab.(:8787/p/5397/anonymous function) (eval at <anonymous> (http://35.195.31.49:8787/p/5397/shared/jquery.min.js:2:2651), <anonymous>:22:279275)
    at HTMLDivElement.eval (eval at <anonymous> (jquery.min.js:formatted:143), <anonymous>:22:32377)
```

note: I get the same error in shiny (chrome and firefox) and in Rstudio native browser

Thank You

**Comment by gpfr** [comment]
It works!

Thank you very much!!
